const CONFIRM_ADD_SAVE_STRING = "내용을 등록하시겠습니까?";
const CONFIRM_EDIT_SAVE_STRING = "내용을 수정하시겠습니까?";
const CONFIRM_SAVE_STRING = "내용을 저장하시겠습니까?";
const CONFIRM_DELETE_SAVE_STRING = "정말 삭제하시겠습니까?";
const CONFIRM_CANCEL_SAVE_STRING = "정말 취소하시겠습니까?";

const COMPLETE_ADD_STRING = "등록이 완료되었습니다.";
const COMPLETE_EDIT_STRING = "수정이 완료되었습니다.";
const COMPLETE_SAVE_STRING = "저장이 완료되었습니다.";
const COMPLETE_DELETE_STRING = "삭제가 완료되었습니다.";
const COMPLETE_CANCEL_STRING = "취소가 완료되었습니다.";

const ERROR_STRING = "에러가 발생했습니다. 잠시 후 다시 시도해주세요.";
const ERROR_NETWORK_STRING = "네트워크 에러입니다.";
const ERROR_SERVER_STRING = "서버 에러입니다.";
const ERROR_UNAUTHORIZED_STRING = "로그인이 필요합니다.";
const ERROR_FORBIDDEN_STRING = "접근이 금지되었습니다.";
const ERROR_BAD_REQUEST_STRING = "잘못된 요청입니다.";
const ERROR_NOT_FOUND_STRING = "해당하는 페이지를 찾을 수 없습니다.";
const ERROR_TIMEOUT_STRING = "요청 시간이 초과되었습니다.";

const LOGOUT_CONFIRM_STRING = "로그아웃 하시겠습니까?";
const LOGOUT_COMPLETE_STRING = "로그아웃 되었습니다.";
const LOGOUT_ERROR_STRING =
  "로그아웃에 실패했습니다. 잠시 후 다시 시도해주세요.";

const SEARCH_PLACEHOLDER_STRING = "검색어를 입력하세요.";
const SEARCH_RESULT_NULL_STRING = "검색 결과가 없습니다.";

const PASSWORD_MIN_LENGTH = 6;
const PASSWORD_MAX_LENGTH = 20;

const SELECTED_NOT_CHECKED = "항목을 선택해주세요.";

const TXT_MAX_LENGTH = 20;
const INPUT_MIN_LENGTH = 2;
const INPUT_MAX_LENGTH = 50;

const REQUIRED_FIELD_MESSAGE = "값을 입력해주세요";

export {
  CONFIRM_SAVE_STRING,
  CONFIRM_ADD_SAVE_STRING,
  CONFIRM_EDIT_SAVE_STRING,
  CONFIRM_DELETE_SAVE_STRING,
  CONFIRM_CANCEL_SAVE_STRING,
  COMPLETE_ADD_STRING,
  COMPLETE_EDIT_STRING,
  COMPLETE_SAVE_STRING,
  COMPLETE_DELETE_STRING,
  COMPLETE_CANCEL_STRING,
  ERROR_STRING,
  ERROR_NETWORK_STRING,
  ERROR_SERVER_STRING,
  ERROR_UNAUTHORIZED_STRING,
  ERROR_FORBIDDEN_STRING,
  ERROR_BAD_REQUEST_STRING,
  ERROR_NOT_FOUND_STRING,
  ERROR_TIMEOUT_STRING,
  LOGOUT_CONFIRM_STRING,
  LOGOUT_COMPLETE_STRING,
  LOGOUT_ERROR_STRING,
  SEARCH_PLACEHOLDER_STRING,
  SEARCH_RESULT_NULL_STRING,
  SELECTED_NOT_CHECKED,
  INPUT_MAX_LENGTH,
  INPUT_MIN_LENGTH,
  TXT_MAX_LENGTH,
  REQUIRED_FIELD_MESSAGE,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
};
